### ISSUE TITLE
Phone config

### ISSUE THREAD

**Issue by Myrkskog** [chayleaf/dotfiles#1]
If I have a working mobile NixOS installed on my oneplus6, could I give your dotfiles a shot and roll back a generation easily if it's miffed?

**Comment by chayleaf** [comment]
You can't really use my system config because it requires UEFI (mobile-nixos doesn't use UEFI on OnePlus 6), but you can use my home config. The home config, however, is heavily wip, so I'm not sure why you'd do that.

**Comment by Myrkskog** [comment]
Ok, I appreciate the quick reply!
