### ISSUE TITLE
Can init for oneplus 6t to use buffyboard console? Thanks.

### ISSUE THREAD

**Issue by gmicroul** [chayleaf/dotfiles#2]

**Comment by chayleaf** [comment]
if you configure an Oneplus 6T to use UEFI, you can indeed use a similar approach

**Comment by gmicroul** [comment]
I just want to know if it can be deployed with mobile nixos (https://github.com/mobile-nixos/mobile-nixos/)configuration file to build the fastboot img.

**Comment by chayleaf** [comment]
it can't be used with Mobile NixOS as-is
